### PR TITLE
Hometask 07

### PR DESCRIPTION
**Pull request by LucasKruschewsky**

### CODE REVIEW

**Review by eduardo-neto-epam — APPROVED** [review]
All evaluation criteria were successfully met

**Review by eduardo-neto-epam — CHANGES_REQUESTED** [review]
I believe you may have forgotten the types for react-redux
Screenshot 2022-05-10 at 11 17 10

**Comment by LucasKruschewsky** [comment]
> I believe you may have forgotten the types for react-redux Screenshot 2022-05-10 at 11 17 10

I didn't have this on my end, but I've just committed the types for react-redux

**Review by eduardo-neto-epam — APPROVED** [review]
&#129305;

**Pull request merged**
